language: java
sudo: false

cache:
  directories:
    - $HOME/.m2

install: true

jdk:
  - openjdk8

script: - travis_wait 30 ./mvnw clean install

notifications:
  email: susmanmaharana.java@gmail.com

before_install:
  - chmod +x mvnw

  